spring:
  application:
    name: opentelemetry-zero-code-instrumentation-practice
otel:
  propagators:
    - tracecontext
    - b3
  resource:
    attributes:
      deployment.environment: dev
      service:
        name: zero-code-instrumentation-practice
        version: 0.0.1
